spring:
  h2:
    console:
      enabled: true
  jpa:
#    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: 386Jeep38622!
    initialization-mode: always
server:
  port: 8060
